extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
env:
  browser: true
rules:
  global-require: 0
  no-underscore-dangle: 0
  import/newline-after-import: 0
  react/jsx-filename-extension:
    - 0
    - extensions:
      - .js